logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
    hibernate: 
      SQL: DEBUG
      type: DEBUG

app: 
  logging-path: D:/todoist/logs
  database-name: todoist
  version: "@project.version@"
  security:
    jwt:
      secret-key: nPeVKgv2NF4HvDi2q2PKqaU2Y+kSlY0OYcP+Evh3A8k=
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 d

server:
  port: 8081
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: -1
spring: 
  datasource: 
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=todoist;encrypt=true;trustServerCertificate=true;
    username: sa
    password: zubayer@123
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
  jpa:
    show-sql : true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate: 
        format_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        id:
          new_generator_mappings: false
  jackson:
    serialization:
      indent-output: true