server: 
  servlet: 
    context-path: /api/v1
    session: 
      persistent: true
      cookie.name: JSESSIONID_TODOIST
  port: 8081

springdoc: 
  default-produces-media-type: application/json

spring:
  servlet: 
    multipart: 
        max-file-size: 50MB
  profiles: 
    active: dev
  application:
    name: TODOIST
